version: "2.2"
services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "127.0.0.1:8007:80"

  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"
    volumes:
      - ./redisdata:/data
    entrypoint: redis-server --appendonly yes

  baza-explorer-back:
    restart: always
    build: ./baza-explorer-backend/
    env_file: ./baza-explorer-backend/.env
    expose:
      - "8000"

  baza-daemon:
    restart: always
    build: ./baza-daemon/
    expose:
      - "11754"
    volumes:
      - ./baza-daemon-data/log:/var/log/bazad
      - ./baza-daemon-data/.Baza:/root/.Baza

  baza-service:
    restart: always
    build: ./baza-service/
    env_file: ./baza-service/.env
    cpus: 0.5
    expose:
      - "8070"
    volumes:
      - ./baza-service-data/log:/var/log/bazaservice
      - ./baza-service-data/wallet:/wallet

  poolserver:
    restart: always
    build: ./poolserver/
    expose:
      - "8117"
      # - "3333"
      # - "5555"
      # - "7777"
    ports:
      - "0.0.0.0:3333:3333"
      - "0.0.0.0:5555:5555"
      - "0.0.0.0:7777:7777"
    volumes:
      - ./poolserver/logs:/pool/logs
    depends_on:
      - redis
      - baza-daemon
      - baza-service

  # haproxy:
  #   restart: always
  #   build: "./haproxy/"
  #   ports:
  #     - "0.0.0.0:3333:3333"
  #     - "0.0.0.0:5555:5555"
  #     - "0.0.0.0:7777:7777"
  # redis-commander:
  #   restart: always
  #   build: "./redis-commander/"
  #   env_file:
  #     - "./redis-commander/.env"
  #   expose:
  #     - "8081"
